### ISSUE TITLE
Support for Django 1.9

### ISSUE THREAD

**Issue by vinaychandra** [agiliq/Django-parsley#75]
Django 1.9 is already released and trying to install Django-parsely would make it rollback to 1.8

**Comment by kmmbvnr** [comment]
Looks like the `ParsleyChoiceFieldRendererMixin` not works on django 1.8+ anymore

TestRadioSelect.test_radio_select is broken

**Comment by Hyperdancer** [comment]
And now we need support for 1.10 :)

**Comment by AliLozano** [comment]
And 1.11 (?)

**Comment by rafaponieman** [comment]
RadioSelect doesn't seem to be working on 1.11:

```
  File "/.../lib/python3.5/site-packages/django/views/generic/edit.py", line 93, in get_context_data
    kwargs['form'] = self.get_form()
  File "/.../lib/python3.5/site-packages/django/views/generic/edit.py", line 45, in get_form
    return form_class(**self.get_form_kwargs())
  File "/.../lib/python3.5/site-packages/parsley/decorators.py", line 78, in new_init
    update_widget_attrs(field, prefix)
  File "/.../lib/python3.5/site-packages/parsley/decorators.py", line 28, in update_widget_attrs
    class ParsleyChoiceFieldRenderer(ParsleyChoiceFieldRendererMixin, field.widget.renderer):
AttributeError: 'RadioSelect' object has no attribute 'renderer
```

**Comment by jproffitt** [comment]
Support for django 1.9-1.11 was added in version 0.7
